name: Deployment-pipeline
on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Get the repository
      - uses: actions/checkout@v4
      - name: Build the app
        run: npm run build

