name: Deployment-pipeline
on:
  push:
    branches:
      - develop
jobs:
  build-and-push:
    #Runner machine hosted by github
    runs-on: ubuntu-22.04
    steps:
      #Get into the directory and install dependencies
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      #Test lint
      - name: Run Lint
        run: npm run lint
      #Build the app for production
      - name: Build the app
        run: npm run build
      #Log into docker hub (Angel main account)
      - name: Log into docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      #Build the image for production
      - name: Build the image for production
        run: docker build -t front:stable .

      #Tag the image for push into docker hub
      - name: Tag the image for pushing into docker hub
        run: docker tag front:stable ${{vars.DOCKERNAME}}/conectasinaloa:front

      - name: Push the image
        run: docker push ${{vars.DOCKERNAME}}/conectasinaloa:front

