name: Deployment-pipeline
on:
  push:
    branches:
      - develop

jobs:

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Check lint
        run: npm run lint

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build the app
        run: npm run build


