name: Deployment-pipeline
on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build The Application
      - uses: actions/checkout@v4

        with:
          fetch-depth: 0

