name: Deployment-pipeline
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Build the app
        run: npm run build

      - name: Log into docker
        uses: docker/login-action@v3

        with:
          username: ${{ env.DOCKERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
