name: onlyssh
on:
  push:
    branches:
      - develop

jobs:
  log:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSHPRIVATEKEY}}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan "${{secrets.SERVERIP}}" > ~/.ssh/known_hosts
          sudo apt-get install sshpass

      - name: Deploy to server
        run: |
          ssh "${{secrets.SERVER}}"